### ISSUE TITLE
ReAnalysis Discussion

### ISSUE THREAD

**Issue by jwbowers** [gsa-oes/1739-GSA-Auctions#1]
@lulachen Some questions for us to discuss:

 - Should we focus on maxbidamt or meanbidamt? 
 - I like using the "bid or not" variable. I'd like to add it to the main analysis.
 - The more I think about it, the more I think that we should dump the logged analysis (despite all of my work, sigh). Perhaps better to focus on the Total Bids and also report rank based tests.
 - The multilevel models (that I ran, to handle lack of independence of blocks because of the same people showing up in different blocks --- i.e. a crossed random effect) show substantively the same results (FYI).

**Comment by lulachen** [comment]
@jwbowers Some more questions for afternoon discussion:

- How should we define "increase bid amount"? Maybe we could give 2 different outcomes, describe how imprecise the mean or max bid estimate is, and give the rank/"bid or not" variable as well which should have a bit more precision, but the precision is not about the dollar amount of the bid.
- Should we make a plot for the abstract?  If so, what kind of plot? 
- How should we describe the estimates, CIs, and what they mean?

**Comment by jwbowers** [comment]
[Dunning_Blocking_ForWeb.pdf](https://github.com/gsa-oes/1739-GSA-Auctions/files/1383767/Dunning_Blocking_ForWeb.pdf)

**Comment by lulachen** [comment]
For abstract -- 
- 2 analysis: 'max bid' and 'bid or not'
- plot about results - treatment vs. control for maximum bids
-description of estimates and CIs -- with ranking/bid or not, CIs are tighter and p-values are smaller.  With max bid, because of 0 skew, CIs are large and more imprecise.
